[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mycelium = "EkTEWy7UYXthM479is4raJKkNfUKe6nqgirf4v6b8vM2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/xeony/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
