[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mycelium = "DWnK5EzB9qHAndpqa2HP4DJQxdiTpwkc1bG2TtSDnb1j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/xeony/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
